let nome = prompt("Qual seu nome completo?")
let nascimento = prompt("Data do seu nascimento *utilize / para separar dia/mês/ano")
let endereco = prompt("Seu endereço atual?")
let cpf = prompt("Qual seu CPF?")
let escolaridade = prompt("Qual seu grau de escolaridade?")
let cnh = prompt("Possui CNH?")
let prole = Number(prompt("Possui quantos filhos?"))
let cargo = prompt("Qual seu cargo atual?")
let salario = Number(prompt("Qual seu salário atual?"))
let comission = Number(prompt("Recebe comissão? Se sim, informe a porcentagem, caso não receba, responda com 0"))
let admissao = Number(prompt("Informe o ano de admissão"))

console.log(typeof nome)
console.log(typeof nascimento)
console.log(typeof endereco)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof cnh)
console.log(typeof prole)
console.log(typeof cargo)
console.log(typeof salario)
console.log(typeof comission)
console.log(typeof admissao)



console.log("O nome do funcionário é", nome)
console.log("Nasceu em", nascimento)
console.log("Mora no endereço", endereco)
console.log("Inscrito no CPF sob número", cpf)
console.log("Seu nível de escolaridade é", escolaridade)
console.log("O mesmo informou que", cnh, "é possuidor de uma CNH")
console.log("Possui", prole, "filho(s)")
console.log("Seu cargo atual é", cargo)
console.log("Seu salário atual é", salario)
console.log("Recebe", comission, "porcento de comissão")
console.log("Admitido em", admissao)